---
# Source: keycloakx/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: default
  labels:
    helm.sh/chart: keycloakx-7.0.1
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
imagePullSecrets:
    []
automountServiceAccountToken: true
