apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
data:
  admin-password: b0w2VEZMSXZMRgo=
  management-password: b0w2VEZMSXZMRgo=
  db-password: b0w2VEZMSXZMRgo=
  local-db-password: a2V5Y2xvYWsK



