version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgresql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    command:
      - "--verbose"
      - "start"
      - "--log-level=INFO,com.fk:trace"
      - "--optimized"
    environment:
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - KC_CACHE=ispn
      - KC_CACHE_STACK=local
      - KC_HTTP_RELATIVE_PATH=/expkeycloak
      - JAVA_OPTS_APPEND=-Xms512m -Xmx1024m
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "80:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  keycloak_data:
  postgres_data: