version: '3'

services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8282:8181"
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "/policies"
    volumes:
      - ./policies:/policies
    restart: unless-stopped